services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    healthcheck: 
      test: ["CMD", "rabbitmqctl","await_startup"]
      interval: 5s

  rest_api:
    image: ruby:3.2.2
    working_dir: /app
    command: bash -c "rm -rf tmp/pids && bin/setup && rails s -b 0.0.0.0 -p 5000"
    ports:
      - "5000:5000"
    volumes:
      - ./rest_api:/app
      - rubygems:/usr/local/bundle
    env_file:
      - ./rest_api/.env
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  
  graphql_api:
    image: ruby:3.2.2
    command: bash -c "cd /app && rm -rf tmp/pids && bin/setup && rails s -b 0.0.0.0 -p 4000"
    ports:
      - "4000:4000"
    volumes:
      - ./graphql_api:/app
      - rubygems:/usr/local/bundle
    env_file:
      - ./graphql_api/.env
    depends_on:
      - rest_api

  web_postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - web_database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s

  web:
    image: ruby:3.2.2
    command: bash -c "cd /app && rm -rf tmp/pids && bin/setup && rails s -b 0.0.0.0"
    ports:
      - "3000:3000"
    volumes:
      - ./web_app:/app
      - rubygems:/usr/local/bundle
    env_file:
      - ./web_app/.env
    depends_on:
      web_postgres:
        condition: service_healthy

  sneakers:
    image: ruby:3.2.2
    command: bash -c "cd /app && WORKERS=PolicyWorker rake sneakers:run"
    volumes:
      - ./rest_api:/app
      - rubygems:/usr/local/bundle
    depends_on:
      - rest_api

  rspec:
    image: ruby:3.2.2
    volumes:
      - ./graphql_api:/graphql_api 
      - ./rest_api:/rest_api
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    command:
      bash -c "cd /graphql_api && bundle install && bundle exec rspec; cd / &&
               cd /rest_api && bundle install && bundle exec rspec"

volumes:
  rubygems:
  database:
  web_database:
  rabbitmq: